#!/bin/sh

# change the desktop number here
FLOATING_DESKTOP_ID=$(bspc query -D -d X)

bspc monitor -d I II III IV V VI VII VIII IX X Code Virt Browser SN MX

xrdb ~/.Xresources

# BSPWM configuration
bspc config border_radius        5
bspc config border_width         3
bspc config window_gap           10
#bspc config top_padding          25
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0

bspc config pointer_motion_interval 1

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer false

#BSPWM coloring

bspc config normal_border_color "$color8"
bspc config active_border_color "$color8"
bspc config focused_border_color "$color3"
bspc config presel_feedback_color "$color3"

bspc rule -a Gimp desktop='IX' state=floating follow=off
bspc rule -a Steam desktop='X' state=floating follow=off
bspc rule -a zoom desktop='VIII' state=floating follow=on

bspc rule -a signal-desktop desktop='MX' follow=off
bspc rule -a slack desktop='MX' follow=off
bspc rule -a discord desktop='MX' follow=off
bspc rule -a rocketchat-desktop desktop='MX' follow=off

# pgrep -x firefox || (bspc rule -a "firefoxdeveloperedition" desktop="Browser" follow=off  && firefox-developer-edition ; bspc rule -r "firefoxdeveloperedition")
sleep 1
# pgrep -x chromium || (bspc rule -a "Chromium" desktop="iNterface" follow=off && chromium ; bspc rule -r "Chromium")

# Autostart
$HOME/.config/polybar/launch.sh

feh --bg-fill ~/.config/wall.pic

case $(hostname -s) in
  moksha)
    pgrep -x dunst || dunst &
    pgrep -x sxhkd || sxhkd &
    #pgrep -x picom || picom  --config ~/.config/picom/picom.conf -b
    pgrep -x xss-lock || xss-lock -l ~/.local/bin/lock.sh &
    pgrep -x nm-applet || nm-applet --indicator
    ;;
  *)
    polybar top &
    ;;
esac

sleep 0.5
notify-send "Bspwm Loaded"

# bspc subscribe node_add | while read -a msg ; do
#   desk_id=${msg[2]}
#   wid=${msg[4]}
#   [ "$FLOATING_DESKTOP_ID" = "$desk_id" ] && bspc node "$wid" -t floating
# done
