#! /bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X Code Virt Browser iNterface Mx

xrdb ~/.Xresources

bspc config border_width         1
bspc config window_gap           15

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer false

bspc config normal_border_color "$background"
bspc config active_border_color "$background"
bspc config focused_border_color "$foreground"
bspc config presel_feedback_color "$foreground"

bspc rule -a Gimp desktop='IX' state=floating follow=off
bspc rule -a Steam desktop='X' state=floating follow=off
bspc rule -a signal-desktop desktop='Mx' follow=off

# Autostart
$HOME/.config/polybar/launch.sh

feh --bg-fill ~/.config/wall.pic

pgrep -x dunst || dunst &
pgrep -x sxhkd || sxhkd &
pgrep -x picom || picom --config ~/.config/picom/picom.conf -b

sleep 0.5
notify-send "Bspwm Loaded"
