#!/bin/sh

# change the desktop number here
FLOATING_DESKTOP_ID=$(bspc query -D -d X)

bspc monitor -d I II III IV V VI VII VIII IX X Code Virt Browser iNterface Mx

xrdb ~/.Xresources

# BSPWM configuration
bspc config border_radius        5
bspc config border_width         1
bspc config window_gap           10
#bspc config top_padding          25
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0

bspc config pointer_motion_interval 1

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer false

#BSPWM coloring

# bspc config normal_border_color "#3c3836"
# bspc config active_border_color "#504945"
# bspc config focused_border_color "#98971a"
# bspc config presel_feedback_color "#504945"

bspc config normal_border_color "$background"
bspc config active_border_color "$background"
bspc config focused_border_color "$foreground"
bspc config presel_feedback_color "$foreground"

bspc rule -a Gimp desktop='IX' state=floating follow=off
bspc rule -a Steam desktop='X' state=floating follow=off
bspc rule -a signal-desktop desktop='Mx' follow=off

pgrep -x firefox || (bspc rule -a "firefoxdeveloperedition" desktop="Browser" follow=off  && firefox-developer-edition ; bspc rule -r "firefoxdeveloperedition")
sleep 1
pgrep -x chromium || (bspc rule -a "Chromium" desktop="iNterface" follow=off && chromium ; bspc rule -r "Chromium")

# Autostart
$HOME/.config/polybar/launch.sh

feh --bg-fill ~/.config/wall.pic

case $(hostname -s) in
  sycamore)
    pgrep -x dunst || dunst &
    pgrep -x sxhkd || sxhkd &
    pgrep -x xss-lock || xss-lock -l ~/.local/bin/lock.sh
    ;;
  moksha)
    pgrep -x dunst || dunst &
    pgrep -x sxhkd || sxhkd &
    pgrep -x picom || picom  --config ~/.config/picom/picom.conf -b
    pgrep -x xss-lock || xss-lock -l ~/.local/bin/lock.sh
    ;;
  *)
    polybar top &
    ;;
esac


sleep 0.5
notify-send "Bspwm Loaded"

bspc subscribe node_add | while read -a msg ; do
  desk_id=${msg[2]}
  wid=${msg[4]}
  [ "$FLOATING_DESKTOP_ID" = "$desk_id" ] && bspc node "$wid" -t floating
done
